/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/homie.gltf");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={23.45}
        position={[-0.06, 1.05, 6.29]}
        rotation={[-0.11, 0.01, 0]}
        scale={[2.31, 7.1, 14.8]}
      />
      <group position={[-2.11, -7.42, -0.38]} scale={0.85}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.skin}
        />
        <points geometry={nodes.Plane_1.geometry} material={materials.skin} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-0.16, 0.48, 0.64]}
        scale={[-0.08, -0.06, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hairbase.geometry}
        material={materials.hairmaterial}
        position={[-2.11, -7.42, -0.38]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["eyebrow.001"]}
        position={[0.06, 0.58, 0.71]}
        rotation={[2.97, -0.07, 1.33]}
        scale={[-0.01, -0.07, -0.01]}
      />
      <group position={[-2.11, -7.42, -0.38]} scale={0.85}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.tshirt}
        />
        <lineSegments
          geometry={nodes.Plane002_1.geometry}
          material={materials.tshirt}
        />
        <points
          geometry={nodes.Plane002_2.geometry}
          material={materials.tshirt}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pant.geometry}
        material={materials.pant}
        position={[-2.11, -7.42, -0.38]}
        scale={0.85}
      />
      <group position={[-2.11, -7.42, -0.38]} scale={0.85}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.shoes}
        />
        <lineSegments
          geometry={nodes.Plane004_1.geometry}
          material={materials.shoes}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["eyebrow.003"]}
        position={[-0.15, 0.58, 0.7]}
        rotation={[-0.17, -0.07, 1.33]}
        scale={[0.01, 0.07, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials["pupil.004"]}
        position={[-0.16, 0.47, 0.69]}
        scale={[-0.02, -0.03, -0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["eyebrow.001"]}
        position={[-0.16, 0.47, 0.68]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.05, 0.05, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials["eyebrow.003"]}
        position={[0.08, 0.49, 0.67]}
        scale={[-0.05, -0.05, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[0.08, 0.49, 0.64]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.08, 0.06, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={materials["pupil.007"]}
        position={[0.08, 0.49, 0.68]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.02, 0.03, 0.01]}
      />
    </group>
  );
}

useGLTF.preload("/homie.gltf");
